
/**************************************************************\
Edition (auto):
##  --/--/---- by generate_exception_header.py

File Name:
##  @file generated_exception_header.hpp

File Description:
##  Header auto generated by the python script at compilation
##  Generated from the files in 'cmake/config/exception/'
##  Used for exception code & message definition
\**************************************************************/

#ifndef GENERATED_EXCEPTION_HEADER_H
    #define GENERATED_EXCEPTION_HEADER_H

    //----------------------------------------------------------------//
    /* INCLUDE */

    #include <iterator>
    #include <cstddef>

namespace utils::exception { // namespace start
//----------------------------------------------------------------//
/* TYPEDEF */

/* Definition of the different exception code */
enum Code {
    Undefined = 0,
    MouseEvent,
    CODE_SENTINEL // sentinel used for verification
};

/* Corresponding exception message for each code */
constexpr inline const char *Message[] = {
    "An undefined error has occured",
    /* MouseEvent */ "Error during the read of the mouse event"
};

// Check at the compile time the correspondece between the message & code
static_assert(std::size(Message) == static_cast<std::size_t>(utils::exception::Code::CODE_SENTINEL), "The message array doesn't correspond to the available exception codes");

} // namespace end

#endif /* GENERATED_EXCEPTION_HEADER_H */
