/**************************************************************\
Edition:
##  @date 06/09/2026 by @author Tsukini

File Name:
##  @file utils.hpp

File Description:
##  Main include for every part of the utils lib
\**************************************************************/

/*
 * _Type/_Types -> _CustomType (already defined/used by the std)
*/

//----------------------------------------------------------------//
/* INCLUDE */

// Only if the redirection from ../utils.hpp was skipped
#ifndef __LIBUTILS_VERSION__
    // Definition of the library version (imported or fallback)
    #if __has_include("version.hpp")
        // Try to include the actual version generated by cmake (failsafe)
        #include "version.hpp"
    #else
        #warning "libutils(__LIBUTILS_VERSION__): utils/version.hpp not found, using fallback value"
        #define __LIBUTILS_VERSION__ "[unknown]" //  (fallback)
    #endif
#endif

//----------------------------------------------------------------//
/* DEFINE */

/* Activate all automatic warning & _deprecated message */
#ifdef _Warning
    #define DEPRECATED_WARNING // _deprecated(...)
    #define LINKER_WARNING // Linker requirement
    #define USAGE_WARNING // Things that should be used carfully
    //#warning "All warnings from 'utils/utils.hpp' are disable"
#endif

#ifdef LINKER_WARNING
    #define BASE64CODEC_LINKER_WARNING
    #define RSAKEY_LINKER_WARNING
    #define AESKEY_LINKER_WARNING
#endif

#ifdef USAGE_WARNING
    #define FATALEXCEPTION_USAGE_WARNING
    #define EETPPARSER_USAGE_WARNING
#endif

/* Desactivate all automatic warning & _deprecated message */
#ifdef _NoWarning
    #define NO_DEPRECATED_WARNING // _deprecated(...)
    #define NO_LINKER_WARNING // Linker requirement
    #define NO_USAGE_WARNING // Things that should be used carfully
    //#warning "All warnings from 'utils/utils.hpp' are disable"
#endif

#ifdef NO_LINKER_WARNING
    #define NO_BASE64CODEC_LINKER_WARNING
    #define NO_RSAKEY_LINKER_WARNING
    #define NO_AESKEY_LINKER_WARNING
#endif

#ifdef NO_USAGE_WARNING
    #define NO_FATALEXCEPTION_USAGE_WARNING
    #define NO_EETPPARSER_USAGE_WARNING
#endif

/* default: if nothing is defined - include everything */
#if !defined(_Handling) && !defined(_Attribute) && !defined(_Tools) && \
    /* _Handling */\
    !defined(_Exception) && !defined(_Verbose) && !defined(_Pool) && !defined(_Cli) && !defined(_Arguments) && !defined(_Network) && \
    /* _Tools */\
    !defined(_Concepts) && !defined(_System) && !defined(_Encapsulation) && !defined(_CustomType) && !defined(_Math) && !defined(_Manip) && !defined(_Algorithms) && !defined(_Security) && \
    /* _Pool */\
    !defined(_Middleware) && \
    /* _Network */\
    !defined(_Socket) && \
    /* _CustomType */\
    !defined(_Vector) && !defined(_BLT) && \
    /* _Math */\
    !defined(_Geometry) && !defined(_Trigo) && \
    /* _Manip */\
    !defined(_IOManip) && !defined(_SManip) && \
    /* _Algorithms */\
    !defined(_C2DMP) && !defined(_SOS) && \
    /* _Security */\
    !defined(_Encryption) && !defined(_Observer)

    #define _Utils
#endif

/* Activate all include */
#ifdef _Utils
    #define _Handling
    #define _Attribute
    #define _Tools
#endif

/* Activate all handling include */
#ifdef _Handling
    #define _Exception
    #define _Verbose
    #define _Pool
    #define _Cli
    #define _Arguments
    #define _Network
#endif

/* Activate all tool include */
#ifdef _Tools
    #define _Math
    #define _Concepts
    #define _Encapsulation
    #define _System
    #define _CustomType
    #define _Manip
    #define _Algorithms
    #define _Security
#endif

/* Activate all pool sub-include */
#ifdef _Pool
    #define _Middleware
#endif

/* Activate all network sub-include */
#ifdef _Network
    #define _Socket
#endif

/* Activate all type sub-include */
#ifdef _CustomType
    #define _BLT // Bidirectional Lookup Table
    #define _Vector
#endif

/* Activate all math sub-include */
#ifdef _Math
    #define _Geometry
    #define _Trigo
#endif

/* Activate all manip sub-include */
#ifdef _Manip
    #define _IOManip
    #define _SManip
#endif

/* Activate all the algorithms */
#ifdef _Algorithms
    #define _C2DMP
    #define _SOS
#endif

/* Activate all the security tools */
#ifdef _Security
    #define _Encryption
    #define _Observer // This define is just to show the obervers exist (need hard import to use)
#endif

//----------------------------------------------------------------//
/* INCLUDE */

/* Exception */
#ifdef _Exception
    // -> Customized exception used for the error/warning handling
    #include "exception/IException.hpp"             // utils::exception::IException
    #include "exception/ExceptionDefine.hpp"        // OK/KO, utils::exception::InternalCode, utils::exception::Type
    #include "exception/basic/NoneException.hpp"    // utils::exception::NoneException
    #include "exception/basic/ErrorException.hpp"   // utils::exception::ErrorException
    #include "exception/basic/WarningException.hpp" // utils::exception::WarningException
    #include "exception/custom/CustomException.hpp" // utils::exception::CustomException
    #include "exception/custom/FatalException.hpp"  // utils::exception::FatalException
#endif

/* Cli */
#ifdef _Cli
    // -> Handling of a customizable command line interface
    #include "cli/Cli.hpp"          // utils::cli::Cli, utils::cli::ParsedData
    #include "cli/Flags.hpp"        // utils::cli::Flag, utils::cli::Flags
#endif

/* Macro */
#ifdef _Attribute
    // -> Define/Macro of attribute & keyword for optimisation & other
    #include "attribute/Attribute.hpp"  // different define/macro for optimisation & other
#endif

/* Verbose */
#ifdef _Verbose
    // -> Define/Macro of verbose usage
    #include "verbose/Verbose.hpp"  // different define/macro for verbose usage
#endif

/* Type */
#ifdef _CustomType
    // -> Multiple custom type
    #include "type/Freezable.hpp"   // utils::type::Freezable
#endif

/* Bidirectional Lookup Table */
#ifdef _BLT
    // -> Bidirectional lookup table (const)
    #include "type/blt/BidirectionalLookupTable.hpp"    // utils::type::BidirectionalLookupTable<L, R, ...>, utils::type::BidirectionalLookupTable<T, ...>
#endif

/* VectorX */
#ifdef _Vector
    // -> Customized vector2 & vector3 for respectively 2 & 3 value of undefined type
    #include "type/vector/Vector.hpp"   // utils::type::IVector<T>, utils::type::VectorN, utils::type::OVectorN
#endif

/* Geometry */
#ifdef _Geometry
    // -> Multiple function to handle computing for angle/point (2D/3D)
    #include "math/MathType.hpp"            // utils::math::* (type)
    #include "math/trigo/Convertion.hpp"    // utils::math::trigo::radToDeg utils::math::trigo::degToRad
    #include "math/geometry/Angle.hpp"      // utils::math::geometry::toLook
    #include "math/geometry/Point.hpp"      // utils::math::geometry::rotatePointND
#endif

/* Trigonometry */
#ifdef _Trigo
    // -> Multiple function to handle computing for angle/point (2D/3D)
    #include "math/MathType.hpp"            // utils::math::* (type)
    #include "math/trigo/Convertion.hpp"    // utils::math::trigo::radToDeg utils::math::trigo::degToRad
#endif

/* Concepts */
#ifdef _Concepts
    // -> Definition of different concepts
    #include "concepts/GlobalConcepts.hpp"      // Global concepts
    #include "concepts/OperationConcepts.hpp"   // Operation concepts
#endif

/* Encapsulation */
#ifdef _Encapsulation
    // -> Different basic tools/comportement encapsulated
    #include "encapsulation/SharedObject.hpp"   // utils::encapsulation::SharedObject
    #include "encapsulation/Pipe.hpp"           // utils::encapsulation::Pipe
    #include "encapsulation/Dup.hpp"            // utils::encapsulation::Dup
    #include "encapsulation/Process.hpp"        // utils::encapsulation::Process
    #include "encapsulation/SharedMemory.hpp"   // utils::encapsulation::SharedMemory
    #include "encapsulation/Poll.hpp"           // utils::encapsulation::Poll
#endif

/* System */
#ifdef _System
    // -> Different basic tools/comportement for global/system use
    #include "system/IdHandler.hpp"     // utils::system::IdHandler
    #include "system/Scheduler.hpp"     // utils::system::Scheduler
    #include "system/LoadBalancer.hpp"  // utils::system::LoadBalancer
#endif

/* Pool */
#ifdef _Pool
    // -> Handling for entity group
    #include "pool/Cluster.hpp" // utils::Cluster<T>
#endif

/* Middleware */
#ifdef _Middleware
    // -> Middlewares handling
    #include "pool/middleware/Middlewares.hpp"  // utils::pool::Middleware<...>, utils::pool::Middlewares<...>
#endif

/* Arguments */
#ifdef _Arguments
    // -> Definition of different thing to handle arguments
    // -> ArgParser: basic check & parsing of arguments
    #include "arguments/ArgParser.hpp"      // utils::arguments::ArgParser
    #include "arguments/ArgParserType.hpp"  // utils::arguments::* (Type)
    #include "arguments/Settings.hpp"       // utils::arguments::Settings (Setting are sub class not public and indidualy used)
    #include "arguments/SettingsDefine.hpp" // utils::arguments::CastType
#endif

/* Network */
#ifdef _Network
    // -> Handling of global network handling and client/server
    // -> Define some special limits and default values
    #include "network/NetworkDefine.hpp"    // different macro et define
    #include "network/NetworkType.hpp"      // different type used for network
    #include "network/Client.hpp"           // utils::network::Client
    #include "network/Server.hpp"           // utils::network::Server
#endif

/* Network - Socket */
#ifdef _Socket
    // -> Handling of socket and tools
    #include "network/socket/Socket.hpp"    // utils::network::socket::ISocket, utils::network::socket::*Socket, utils::network::socket::* (tools)
#endif

/* Input/Output - Manip */
#ifdef _IOManip
    // -> Handling of input/output manipulation
    // -> Define some special char & other, ANSI escape sequences, ...
    #include "manip/iomanip/Color.hpp" // utils::iomanip::Color, utils::iomanip::BackColor
    #include "manip/iomanip/Char.hpp"  // utils::iomanip::Char
    #include "manip/iomanip/Style.hpp" // utils::iomanip::Style, utils::iomanip::ResetStyle
    #include "manip/iomanip/ANSI.hpp"  // different inline function for ANSI escape sequences
#endif

/* String - Manip */
#ifdef _SManip
    // -> Handling of string manipulation
    #include "manip/smanip/format.hpp"        // utils::smanip::format
    #include "manip/smanip/codec/Codec.hpp"   // utils::smanip::codec::ICodec, utils::smanip::codec::*Codec
    #include "manip/smanip/parser/Parser.hpp" // utils::smanip::parser::IParser, utils::smanip::parser::*Parser
#endif

/* c2dmp-hsm */
#ifdef _C2DMP
    // -> c2dmp-hsm: heuristic string matching
    #include "algorithms/c2dmp-hsm/c2dmp-hsm.hpp"               // utils::algorithms::c2dmp::c2dmp
    #include "algorithms/c2dmp-hsm/algorithm/optimized.hpp"     // utils::algorithms::c2dmp::c2dmp_optimized
    #include "algorithms/c2dmp-hsm/algorithm/simplified.hpp"    // utils::algorithms::c2dmp::c2dmp_simplified
    #include "algorithms/c2dmp-hsm/algorithm/foptimized.hpp"    // utils::algorithms::c2dmp::c2dmp_foptimized
    #include "algorithms/c2dmp-hsm/algorithm/fsimplified.hpp"   // utils::algorithms::c2dmp::c2dmp_fsimplified
#endif

/* s.o.s */
#ifdef _SOS
    // -> s.o.s: steganography optimized and securized
    #include "algorithms/sos/sos.hpp"                           // utils::algorithms::sos::sos_embed, utils::algorithms::sos::sos_extract, utils::algorithms::sos::tools::* (convert tools), utils::algorithms::sos::* (default type)
    #include "algorithms/sos/algorithm/embed_optimized.hpp"     // utils::algorithms::sos::sos_embed_optimized
    #include "algorithms/sos/algorithm/extract_optimized.hpp"   // utils::algorithms::sos::sos_extract_optimized
    #include "algorithms/sos/tools/convert.hpp"                 // utils::algorithms::sos::to_bytes, utils::algorithms::sos::bytes_to
#endif

/* Security */
#ifdef _Security
    // -> Handling of multiple security tools
#endif

/* Security - Encryption */
#ifdef _Encryption
    // -> Handling of multiple encryption tools
    #include "security/encryption/Key.hpp"  // utils::security::encryption::IKey<t>, utils::security::encryption::RSAKey/CommonRSAKey, utils::security::encryption::AESKey
#endif
